### ISSUE TITLE
Having less framewidth for the window

### ISSUE THREAD

**Issue by UtakarshAgg** [janbodnar/Java-Breakout-Game#1]
Ok so the problem is when i tried to run this setup in my laptop offline, i saw that the window appering is 14 pixels less than what is there.
i can see the paddle and ball go inside the right wall of the frame for upto 14 pixels
![image](https://user-images.githubusercontent.com/53621232/62415364-5ca82480-b646-11e9-8fe0-af712fa175c2.png)

**Comment by janbodnar** [comment]
What is your OS and resolution? Is it different if you use it on different computer?

**Comment by UtakarshAgg** [comment]
Windows 10 Home 
1920 x 1080
havent tried that on different computers

This problem occured in right wall as well as bottom of this frame.. its just that i editted that part

**Comment by janbodnar** [comment]
Fixed.

**Comment by UtakarshAgg** [comment]
Where was the problem actually i did like to know

**Comment by janbodnar** [comment]
The problem was that the width of the window was set to a fixed value -- 300 px; however, 
windows have various decorations on various OS and environments. The correct way
to do it is to set the board width to a preferred size and call `pack()` on the frame. 
The preferred size is respected and decorations of various widths are generated around 
the board/panel.
